name: Publish Package to npmjs
on:
  workflow_dispatch:

jobs:
  build:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["18.x"]
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          always-auth: true
          cache: "pnpm"
          node-version: ${{ matrix.node-version }}
          registry-url: "https://registry.npmjs.org"

      - run: pnpm install --frozen-lockfile
      - run: pnpm tsc --noEmit
      - run: pnpm build

      # Publish NPM
      - run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.YARN_TOKEN }}

      # Publish GHPR
      # - uses: actions/setup-node@v3
      #   with:
      #     registry-url: "https://npm.pkg.github.com"
      #     always-auth: true
      #     node-version: "16.x"

      # - run: yarn publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}